### ISSUE TITLE
量化我的onnx文件时出现，AttributeError: FLOAT8E4M3FN

### ISSUE THREAD

**Issue by scuizhibin** [inisis/OnnxSlim#16]
环境版本
onnx                             1.13.0
onnx-graphsurgeon      0.3.12
onnxruntime                 1.18.0
onnxslim                      0.1.29
numpy                         1.21.0

[bevformer.zip](https://github.com/user-attachments/files/16049249/bevformer.zip)

**Comment by inisis** [comment]
This is a compatiblity problem, please upgrade your onnx version to 1.16.

**Comment by scuizhibin** [comment]
[bevformerencodertrt.zip](https://github.com/user-attachments/files/16060781/bevformerencodertrt.zip)
这个是优化前的onnx，使用tensorrt8.5.2量化是没有问题的，但是使用onnxslim优化过后 就会出现问题 operation.cpp:203: DCHECK(!i->is_use_only()) failed.

**Comment by scuizhibin** [comment]
这个是TENSORRT版本问题，降低版本就行使用8.4。
