### ISSUE TITLE
Error when trying to slim Qwen2VL vision encoder: `ValueError: list.remove(x): x not in list`

### ISSUE THREAD

**Issue by xenova** [inisis/OnnxSlim#49]
When trying to run onnxslim on [this model](https://huggingface.co/hf-internal-testing/tiny-random-Qwen2VLForConditionalGeneration/blob/main/onnx/vision_encoder.onnx), I get the following error `ValueError: list.remove(x): x not in list`.

Version: `onnxslim-0.1.41`

Code to reproduce:
```
wget https://huggingface.co/hf-internal-testing/tiny-random-Qwen2VLForConditionalGeneration/resolve/main/onnx/vision_encoder.onnx
onnxslim vision_encoder.onnx slimmed.onnx
```

Error message:
```
Onnx Runtime version 1.20 has no specified compatible ONNX version.
Traceback (most recent call last):
  File "/usr/local/bin/onnxslim", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.10/dist-packages/onnxslim/cli/_main.py", line 147, in main
    slim(
  File "/usr/local/lib/python3.10/dist-packages/onnxslim/cli/_main.py", line 89, in slim
    model = optimize(model, skip_fusion_patterns)
  File "/usr/local/lib/python3.10/dist-packages/onnxslim/core/__init__.py", line 154, in optimize
    model = optimize_model(graph, skip_fusion_patterns)
  File "/usr/local/lib/python3.10/dist-packages/onnxslim/core/optimization/__init__.py", line 27, in optimize_model
    dead_node_elimination(graph)
  File "/usr/local/lib/python3.10/dist-packages/onnxslim/core/optimization/dead_node_elimination.py", line 18, in dead_node_elimination
    dead_node_elimination(subgraph, is_subgraph=True)
  File "/usr/local/lib/python3.10/dist-packages/onnxslim/core/optimization/dead_node_elimination.py", line 35, in dead_node_elimination
    delete_node(node)
  File "/usr/local/lib/python3.10/dist-packages/onnxslim/core/utils.py", line 21, in delete_node
    feed.outputs.remove(node.inputs[input_var_idx])
  File "/usr/local/lib/python3.10/dist-packages/onnxslim/third_party/onnx_graphsurgeon/util/misc.py", line 210, in remove
    super().remove(x)
ValueError: list.remove(x): x not in list
```

**Comment by inisis** [comment]
Thanks for your findings, I will check this very soon.

**Comment by inisis** [comment]
Hi @xenova do you have scripts to test if the model works, onnxslim will generate random data if inputs are in fixed shape but not dynamic one.

**Comment by inisis** [comment]
> Adding a simple check to see if the list contains the node seems to fix it, but maybe there are other places to change this too.
> 
> ```
> Onnx Runtime version 1.20 has no specified compatible ONNX version.
> unable to remove list.remove(x): x not in list
> +---------------------+-----------------------------------------+-----------------------------------------+
> |     Model Name      |           vision_encoder.onnx           |              slimmed.onnx               |
> +---------------------+-----------------------------------------+-----------------------------------------+
> |     Model Info      |       Op Set: 14 / IR Version: 7        |       Op Set: 14 / IR Version: 7        |
> +---------------------+-----------------------------------------+-----------------------------------------+
> |  IN: pixel_values   | float32: ('batch_size * grid_t * grid_h | float32: ('batch_size * grid_t * grid_h |
> |                     |          * grid_w', 'channel *          |          * grid_w', 'channel *          |
> |                     |   temporal_patch_size * patch_size *    |   temporal_patch_size * patch_size *    |
> |                     |              patch_size')               |              patch_size')               |
> |    IN: grid_thw     |        int64: ('batch_size', 3)         |        int64: ('batch_size', 3)         |
> | OUT: image_features | float32: ('batch_size * grid_t * grid_h | float32: ('batch_size * grid_t * grid_h |
> |                     |             * grid_w', 16)              |             * grid_w', 16)              |
> +---------------------+-----------------------------------------+-----------------------------------------+
> |         Add         |                   25                    |                   25                    |
> |        Cast         |                   39                    |                    3                    |
> |       Concat        |                   26                    |                   19                    |
> | ConcatFromSequence  |                    1                    |                    1                    |
> |      Constant       |                   262                   |                    0                    |
> |   ConstantOfShape   |                   18                    |                   18                    |
> |        Conv         |                    1                    |                    1                    |
> |         Cos         |                    1                    |                    1                    |
> |       CumSum        |                    1                    |                    1                    |
> |         Div         |                   14                    |                   14                    |
> |       Einsum        |                    1                    |                    1                    |
> |        Equal        |                   12                    |                   12                    |
> |         Erf         |                    1                    |                    1                    |
> |       Expand        |                   15                    |                   15                    |
> |       Flatten       |                    1                    |                    1                    |
> |       Gather        |                   22                    |                   22                    |
> |        Gemm         |                   10                    |                   10                    |
> |      Identity       |                    2                    |                    2                    |
> |         If          |                    2                    |                    2                    |
> |        Loop         |                    1                    |                    1                    |
> |       MatMul        |                    4                    |                    4                    |
> |         Mul         |                   33                    |                   33                    |
> |         Neg         |                    4                    |                    4                    |
> |         Pad         |                    1                    |                    1                    |
> |         Pow         |                    5                    |                    5                    |
> |        Range        |                    9                    |                    9                    |
> |      ReduceMax      |                    1                    |                    1                    |
> |     ReduceMean      |                   10                    |                   10                    |
> |       Reshape       |                   23                    |                   20                    |
> |      ScatterND      |                    2                    |                    2                    |
> |     SequenceAt      |                    2                    |                    2                    |
> |    SequenceEmpty    |                    1                    |                    1                    |
> |   SequenceInsert    |                    1                    |                    1                    |
> |        Shape        |                   39                    |                   20                    |
> |       Sigmoid       |                    2                    |                    2                    |
> |         Sin         |                    1                    |                    1                    |
> |        Slice        |                   24                    |                   20                    |
> |       Softmax       |                    2                    |                    2                    |
> |        Split        |                    4                    |                    4                    |
> |   SplitToSequence   |                    2                    |                    2                    |
> |        Sqrt         |                   11                    |                    9                    |
> |       Squeeze       |                   14                    |                   14                    |
> |         Sub         |                    5                    |                    5                    |
> |        Tile         |                    3                    |                    3                    |
> |      Transpose      |                   13                    |                   13                    |
> |      Unsqueeze      |                   60                    |                   33                    |
> |        Where        |                   12                    |                   12                    |
> +---------------------+-----------------------------------------+-----------------------------------------+
> |     Model Size      |                203.76 KB                |                192.46 KB                |
> +---------------------+-----------------------------------------+-----------------------------------------+
> |    Elapsed Time     |                                      0.68 s                                       |
> +---------------------+-----------------------------------------+-----------------------------------------+
> ```

@xenova I think this slimmed model is invalid, you can use patch here https://github.com/inisis/OnnxSlim/pull/50

**Comment by xenova** [comment]
That fixes it! Thanks! If possible, could you put out a new release for this? I'm releasing Transformers.js v3.1 soon and would be nice to have this ready by then.

**Comment by xenova** [comment]
Ah spoke too soon, looks like the error still persists.
```
pip install --upgrade git+https://github.com/inisis/OnnxSlim.git@dev
wget https://huggingface.co/hf-internal-testing/tiny-random-Qwen2VLForConditionalGeneration/resolve/main/onnx/vision_encoder.onnx
onnxslim vision_encoder.onnx
```

produces:
```
Traceback (most recent call last):
  File "/usr/local/bin/onnxslim", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.10/dist-packages/onnxslim/cli/_main.py", line 158, in main
    slim(
  File "/usr/local/lib/python3.10/dist-packages/onnxslim/cli/_main.py", line 102, in slim
    model = optimize(model, skip_fusion_patterns)
  File "/usr/local/lib/python3.10/dist-packages/onnxslim/core/__init__.py", line 155, in optimize
    model = optimize_model(graph, skip_fusion_patterns)
  File "/usr/local/lib/python3.10/dist-packages/onnxslim/core/optimization/__init__.py", line 27, in optimize_model
    dead_node_elimination(graph)
  File "/usr/local/lib/python3.10/dist-packages/onnxslim/core/optimization/dead_node_elimination.py", line 18, in dead_node_elimination
    dead_node_elimination(subgraph, is_subgraph=True)
  File "/usr/local/lib/python3.10/dist-packages/onnxslim/core/optimization/dead_node_elimination.py", line 35, in dead_node_elimination
    delete_node(node)
  File "/usr/local/lib/python3.10/dist-packages/onnxslim/core/utils.py", line 21, in delete_node
    feed.outputs.remove(node.inputs[input_var_idx])
  File "/usr/local/lib/python3.10/dist-packages/onnxslim/third_party/onnx_graphsurgeon/util/misc.py", line 210, in remove
    super().remove(x)
ValueError: list.remove(x): x not in list
```

**Comment by inisis** [comment]
![image](https://github.com/user-attachments/assets/b57d0da5-16e5-4894-92b8-c0bcae3bae40)
I think it works for me.

**Comment by xenova** [comment]
Hmm, weird. Which versions of onnx/onnxruntime are you using? 👀

**Comment by inisis** [comment]
@xenova Hi, I watched your video https://www.youtube.com/watch?v=n18Lrbo8VU8, very impressive work, btw, can I get one HF T-shirt 😀

**Comment by inisis** [comment]
Here is my version info

![image](https://github.com/user-attachments/assets/9d31b15f-a5e4-4ac1-a847-355595d17792)

**Comment by xenova** [comment]
A clean install fixed it! ❤️ Thank you!

> btw, can I get one HF T-shirt 😀

I'm sure we can organize something! Send me a DM on X or LinkedIn! 🤗

**Comment by xenova** [comment]
You're an absolute legend! Thank you!
